### ISSUE TITLE
Problem coming 

### ISSUE THREAD

**Issue by krivadna** [0xKayala/Shodanizer#2]
Does it run only on non rooted
Devices?

I use termux non rooted and unable to run with commands shodanizer -h Shodanizer -h 

~/Shodanizer $ bash Shodanizer.sh

   _____ __              __            _
  / ___// /_  ____  ____/ /___ _____  (_)___  ___  _____
  \__ \/ __ \/ __ \/ __  / __ `/ __ \/ /_  / / _ \/ ___/
 ___/ / / / / /_/ / /_/ / /_/ / / / / / / /_/  __/ /
/____/_/ /_/\____/\__,_/\__,_/_/ /_/_/ /___/\___/_/  v1.0.0

                            Made by Satya Prakash (0xKayala)

Scanning domain:
Error: Unable to parse JSON response
Shodan Scan is completed

**Comment by 0xKayala** [comment]
You need to have Shodan installed on your device and for termux the home directory will be different, so find where the /usr/bin/ is located in your termux and move the shodanizer.sh file to /usr/bin/ location after you gave the execute permissions to the shodanizer.sh file. Then it will work for sure.
